### ISSUE TITLE
How would you use your library to build an oscilloscope?

### ISSUE THREAD

**Issue by wfdudley** [AntonioPrevitali/DueAdcFast#1]
Thanks for doing the work on this library.
I've made an oscilloscope using your library with an 800x480 display.

Below is my pseudo-code.  It works, but it's clunky and I doubt it's the best way.
How would you solve the following problems?

1. How to change acquisition speed and number of channels (without rebooting) ?
can I `Stop()` and `Start()` acquisition whenever number of channels or timebase changes?
It seems to work, but you don't recommend it.
2. If acquisition is left running, does it fill the allocated memory circularly?  If one
calls `getMeasures()` over and over again, are the returned values all in proper time order? 
3. Is there a better way to tell when a minimum number of samples have been
acquired without calling `MeasureSpeed()` ?  Calling `delay()` is hacky.

## pseudo-code for scope

`// run the constructor based on maximum number of channels:`
`DueAdcFast DueAdcF(1024 * MAX_CHAN);`

`while(1) {`
> `// get number of channels from user interface`
   `// get timebase from user interface`
   `// get trigger channel, slope, level & mode from user interface`

> `if (trigger mode is "normal") {`
> > `while(trigger condition not satisfied) {`   
> > > `read input from trigger channel using DueAdcF.oldAnalogRead()`
         `compare to trigger condition (slope, value)`
         `if (trigger condition satisfied) {`
> > > > `break`

> > > `}`

> > `}` 

> `}`
   `// based on enabled channels, turn pins on and off using`
   `// DueAdcF.EnablePin() and  DueAdcF.DisEnabPin()`
   `turn_pins_on_or_off();`

> `// compute divisor from timebase and number of channels`
   `divisor = compute_divisor(timebase, nChan);`
> `{     // block so allocated memory is deleted`
> >   `// start acquisition`
  `DueAdcF.Start(divisor);`
  `// wait for enough samples to be collected`
  `DueAdcF.MeasureSpeed();`
  `// stop acquisition`
  `DueAdcF.Stop();`
  `// allocate memory for measurements (size x number-of-channels):`
  `DueAdcFastMeasure lastMeas[DATA_SIZE * nChan];`
  `// get the data:`
  `DueAdcF.getMeasures(DATA_SIZE * nChan, lastMeas, &xtime);`
  `// display values in lastMeas on screen`
  `display_data();`

> `} // lastMeas[] is freed`

`}`

**Comment by AntonioPrevitali** [comment]
Of course this is not a problem!
This is a request for advice!
So first sight I have this idea, use GetPosCurr(void)
when the oscilloscope trace should start.
Wait as long as it takes for the trace to complete (with delay example but not with MeasureSpeed, MeasureSpeed is just for testing)
use FindAvgForPinPos(uint32_t xpos,uint8_t pin,uint16_t pSkip, 1)  pSkip 0 to n measure after xpos...
You need enough memory to prevent the data from being overwritten, or you can load the data into another memory and then use that to update the display.
It is also possible to use the stop.
This is just an idea but I'm sure you will do a great job even without my advice.
It is also feasible to add a new method to the library that returns the measures as getMeasures starting from the position obtained with GetPosCurr(void)
