### ISSUE TITLE
EnableDif(A9) does not work.

### ISSUE THREAD

**Issue by cnassar82** [AntonioPrevitali/DueAdcFast#3]
Hello,

First of all, thank you for such a great library.  

I'm trying to use differential mode on pins A8 and A9, and it does not seem to work.  I have no trouble using A1-A7. As far as I can tell, the pins do not get enabled when attempting to use A9. Single ended mode seems to work fine.  

Any help would be appreciated!

**Comment by AntonioPrevitali** [comment]
If you write EnableDif(A9) in your code this won't work.
To obtain DIFF A8 - A9 must write EnableDif(A8) e
ReadAnalogPin(A8) as indicated in the documentation.

**Comment by cnassar82** [comment]
Thank you!
EnableDif(A8) works perfectly.  I must have missed it in the documentation.
