### ISSUE TITLE
only get 2k samples per second

### ISSUE THREAD

**Issue by yanxiang-wang** [AntonioPrevitali/DueAdcFast#4]
Hi,
I tried to run the sample 1 code on the Arduino Due, but I only got around 2k samples from the serial port.
I use the serial port monitor in the Arduino IDE to check. Is there anything wrong with my operations?

**Comment by AntonioPrevitali** [comment]
The serial port is not fast enough to support the potential data flow that DueAdcFast can produce.
Even processing the stream locally without transmitting the data externally is often slower.
Normally the way I use it is to observe for a certain period of time and collect the data in the bufferAdc.
Then I stop the collection, and slowly over time I go to analyze what happened.
Imagine an oscilloscope capturing the waveform by loading the data with dueadcfast into its buffer. and then calmly analyzes them and draws the waveform.
With this answer I consider the problem you reported closed.
